j0k3r/php-readability

README.md
composer.json
tests/ReadabilityTest.php

Remove Tidy _hard_ deps since the lib is supposed to work without it.
Fix #9

Remove tidy from requirement

---

.travis.yml
src/Readability.php
tests/ReadabilityTest.php

We append a new node when it isn't a `div` or `p` (like when it's an `article`) with the same id which generate a DOM error "_DOMElement::setAttribute(): ID blabla already defined"_.
This should fix https://github.com/wallabag/wallabag/issues/1632

Avoid adding id that might already exists

---

src/Readability.php
tests/ReadabilityTest.php

- avoid method signature update
- revert moving logic out of the constructor

Revert BC changes

---

src/Readability.php

Some links got a “tooltip-link” and shouldn’t be removed by php-readability because they are usefull to the content

Don’t be too agressive

---

src/JSLikeHTMLElement.php
tests/ReadabilityTest.php

This isn't the best solution but the previous one using `@` wasn't really better.
Appending a string into a fragment might generate some warning if the string contains bad entity.
For example `&plus;`.
Fix https://github.com/j0k3r/php-readability/issues/29

Avoid php warning

---

.travis.yml
tests/ReadabilityTest.php

- Add a build for 7.3, just in case.
- Update PHPUnit to work on PHP 7.2.
- Remove `sudo: false` to use the new Travis infra.

Updating to 7.2

---

.php_cs
.travis.yml
composer.json

Bump composer dependencies and move php-cs to v2.
Also remove Travis tests and stuff related to php < 5.6. Move php-cs to php 7.2 and don't allow failures on 7.3 anymore.
Tests will fail, because #42 is not merged yet.

Composer bump, php-cs bump to v2, travis update

---

src/Readability.php

A change released in tidy 5.6.0 breaks php-tidy when using
tidy_parse_string+tidy_clean_repair and wrap=0, incorrectly wrapping
every single word. Also it seems that $tidy->value should not be used to
retrieve the repaired html as far as it is undocumented and for internal
use.
We replace the call with tidy_repair_string which directly returns the
repaired string.
Relates to https://github.com/htacg/tidy-html5/issues/673
Relates to https://bugs.php.net/bug.php?id=75947
Fixes https://github.com/wallabag/wallabag/issues/3872
Tests pass.

tidy: use tidy_repair_string instead of tidy_parse_string+tidy_clean_repair

---

.editorconfig
.gitattributes
.gitignore
.scrutinizer.yml
.travis.yml
composer.json
phpunit.xml.dist
src/Readability.php

`electrolinux/php-html5lib` was quite old and incompatible with the upcoming Composer 2.0.
Jumping to `masterminds/html5` for the same result. Also the lib is maintained.
Also:
- keep README in vendors
- use new Scrutinizer engine
- test with lower deps
- remove php-coveralls dev deps and download the phar during the CI build
Fix #56 (poke @jtojnar)

Use a new deps for HTML5 parser

---

src/Readability.php

HTML 4.01 Strict only allows block-level elements within `noscript`, form and blockquote. The `enclose-block-text` option fixes the instances when those elements contain inline elements or text by wrapping the children in paragraphs.
HTML 5 has looser content model and allows `noscript` elements basically anywhere, including paragraphs, making the `noscript` elements inherit the parent element’s content model. This means that tidy will produce invalid HTML nesting paragraphs for `p > noscript > text`, a structure that would be invalid on two counts in HTML 4 Strict profile but is completely valid in HTML 5.
Popular WordPress image lazy-loading code produces precisely that structure so tidy “corrects” it to invalid code. In a proper HTML parser, the produced code would force close the …

readability: stop tidy from wrapping noscript text

---

tests/ReadabilityTest.php

- Using assertSame to make assertion equal strict.

Using assertSame to make assertion equal strict

---

src/Readability.php
tests/ReadabilityTest.php

This PR backports several things from mozilla/readability, including:
* Add child score to all ancestors instead of the first parent only
* Check 5 top candidates and try to find alternative candidates within ancestors, this can help to find a better parent and grab more content
* Reduce patterns for `unlikelyCandidates` to the one used by Mozilla as ours tend to remove useful nodes, see example below
* Score headers (_h2 to h6_) by default in addition to div, p, td and section
As a consequence, two tests fail as some nodes are now kept (`class="clock"`).
In these tests the parent has a `display:none`, which was a pattern of `unlikelyCandidates`.
Mozilla's Readability has a specific routine to remove invisible nodes.
A similar routine seems to exist in Graby but not in our version of …

Improvements / backports from mozilla/readability

---

src/Readability.php

It also disables reverting forced paragraph elements as it can break
layouts or corrupt content.

Fix `isPhrasingContent` conditions, text node replacement

---

src/Readability.php

Huge tags can lead to a failure of preg_replace, thus erasing the whole
fetched content.
E.g.: https://slate.com/news-and-politics/2020/08/joe-biden-empathy-candidate.html
Fixes https://github.com/wallabag/wallabag/issues/5847

Strip script and style tags through `::clean()` method instead of `preg_replace`

---

.github/workflows/coding-standards.yml
.github/workflows/continuous-integration.yml
.php-cs-fixer.php
composer.json
rector.php
src/Readability.php
tests/ReadabilityTest.php

This will allow us to use flexible heredocs in test,
as well as typed properties and other goodies.
https://www.php.net/releases/7_3_0.php
https://www.php.net/releases/7_4_0.php
Picked from #87
Depends on #86

Require PHP 7.4

---

src/Readability.php

It would fail for e.g. `<div> <p>foo</p> </div>`.
mozilla/readability uses children for the tag lookup, which return only elements. PHP does not have children property so b580cf216d9001f82c866bb9a6c8bcad1cc862d8 mistakenly used `childNodes` instead, but that can return any node type.
Let’s filter the children ourselves.
Also add comments from mozilla/readability’s `_hasSingleTagInsideElement`.
Picked from https://github.com/j0k3r/php-readability/pull/87

Fix hasSingleTagInsideElement method

---

.github/workflows/continuous-integration.yml
src/Readability.php
tests/ReadabilityTest.php

PHP 8.4 is in beta, with final version scheduled for November so it is time to start testing it.

ci: Fix & add PHP 8.4

---

src/Readability.php

`DOMNodeList` implements `Traversable`.
There are some `for` loops left but we cannot simply replace those: PHP follows the DOM specification, which requires that `NodeList` objects in the DOM are live. As a result, any operation that removes a node list member node from its parent (such as `removeChild`, `replaceChild` or `appendChild`) will cause the next node in the iterator to be skipped.
We could work around that by converting those node lists to static arrays using `iterator_to_array` but not sure if it is worth it.
Also add few cleanups I noticed.

Iterate node lists with foreach

---

src/Readability.php
tests/ReadabilityTest.php

`DOMDocument::loadHTML` will parse HTML documents as ISO-8859-1 if there is no `meta[charset]` tag. This means that UTF-8-encoded HTML fragments such as those coming from JSON-LD `articleBody` field would be parsed with incorrect encoding.
In f14428e4c0fa34b28f6b8a7696e62790bcde363e, we tried to resolve it by putting `meta[charset]` tag at the start of the HTML fragment. Unfortunately, it turns out that causes parser to auto-insert a `html` element, losing the attributes of the original `html` tag.
Let’s try to insert the `meta[charset]` tag into the proper place in the HTML document.
We do not need to use the same trick with `JSLikeHTMLElement::__set` since that expects smaller HTML fragments, not `html` documents, so creating `html` and `head` elements will not be a problem.
Also …

Fix discarding `html[lang]`

---

src/Readability.php
tests/ReadabilityTest.php

Backports https://github.com/j0k3r/php-readability/pull/102, #104

[1.x] Backport parser_url + html[lang] fixes

---

src/Readability.php
tests/ReadabilityTest.php

Fix character decoding regression when `title` precedes `meta[charset]`
Because of PHP 8.2 deprecation, in f14428e4c0fa34b28f6b8a7696e62790bcde363e, we stopped converting non-ASCII characters to HTML entities. Instead, we started to explicitly insert `meta[charset]` tag at the start of the document.
Later, we discovered that was breaking `html[lang]` so, in efbbc86df9716a3ab1ed8a351d9e8316f3a2aab0, we made the insertion smarter. One of the improvements was that it would not insert the `meta[charset]` tag when it was already present.
That, however, broke websites that had `title` tag before `meta[charset]`. On those, libxml2 would decode the `title` contents as ISO-8859-1.
We could improve the logic (e.g. check that there is not text content before `meta[charset]`) or insert the tag …

Fix character decoding regression when `title` precedes `meta[charset]`
